//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_StorePhone3.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class spec
    {
        public spec()
        {
            this.productdetails = new HashSet<productdetail>();
            this.specdetails = new HashSet<specdetail>();
        }
    
        public int id { get; set; }
        public int activeFlag { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual ICollection<productdetail> productdetails { get; set; }
        public virtual ICollection<specdetail> specdetails { get; set; }
    }
}
